apiVersion: v1
kind: Service
metadata:
  name: {{ include "genai-toolbox.fullname" . }}
  labels:
    {{- include "genai-toolbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.options.port }}
      targetPort: {{ .Values.options.port }}
  selector:
    {{- include "genai-toolbox.selectorLabels" . | nindent 4 }}
